### ISSUE TITLE
启动crash

### ISSUE THREAD

**Issue by Brances** [misaka14/v2ex-OC#4]
* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'
Xcode 8.3.2  手机版本8.3

**Comment by Brances** [comment]
好像是3DTouch引起的原因，我注释掉就没事了。

**Comment by misaka14** [comment]
谢谢使用，3DTouch目前只做了样式在上面，目前没有添加功能，以后会添加
